[workspace]
authors = ["SÃ¸ren Heidelbach <shei@bio.aau.dk>"]
channels = ["conda-forge","bioconda"]
name = "nanomotif"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
wheel = "*"
requests = "*"
numpy = ">=1.24.4,<=2.0.0"
pandas = ">=2.0.2"
polars = ">=1.31"
scipy = ">=1.10.1"
scikit-learn = ">=1.5.2"
networkx = ">=3.1"
pyarrow = ">=15.0.2"
epimetheus-py = "==0.7.5"
hdbscan = "*"
Bio = ">=1.6.2"
snakemake = ">=7.32.4"
progressbar2 = ">=3.53.1"
pyfastx = ">=0.2.10"
pysam = ">=0.22.0"
regex = ">=2025.10.23"
pyinstrument = ">=5.1.1"

[pypi-dependencies]
nanomotif = {path = ".", editable = true}

[environments]
test = ["test"]

[feature.test.dependencies]
pytest = ">=7.4.0"
hypothesis = ">=6.148.2"
pluggy = ">=1.6.0"
